/**
 * Re-fetch the self-hosted type from the Google Fonts API.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Downloads only the subsets the app actually renders, collapses the variable
 * families to one file each, and rewrites public/fonts.css. Licence files in
 * public/fonts/ are not touched — see the README there before adding a family.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public/fonts");

const QUERY =
  "family=Archivo:wght@400;600;700" +
  "&family=IBM+Plex+Mono:wght@400;600;700" +
  "&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600" +
  "&display=swap";
// The API returns woff2 with unicode-range only for a browser user agent.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) if (f.endsWith(".woff2")) unlinkSync(join(OUT, f));

const css = execFileSync("curl", [
  "-sS", "--fail", "-A", UA, `https://fonts.googleapis.com/css2?${QUERY}`,
]).toString();

// Archivo and Source Serif 4 are variable: Google returns one file for every
// requested weight. Declaring a weight range serves one file instead of three.
// IBM Plex Mono is static, so each weight is a separate file.
const PLAN = {
  Archivo:          { slug: "archivo",      variable: true,  subsets: ["latin", "latin-ext"], stretch: "100%" },
  "IBM Plex Mono":  { slug: "plex-mono",    variable: false, subsets: ["latin", "latin-ext"] },
  // The serif only ever sets statement text, which is ASCII plus latin-range
  // punctuation, so latin-ext would be 100KB that never renders.
  "Source Serif 4": { slug: "source-serif", variable: true,  subsets: ["latin"] },
};

const blocks = css.split("/*").slice(1).map((b) => {
  const subset = b.slice(0, b.indexOf("*/")).trim();
  const body = b.slice(b.indexOf("*/") + 2);
  return {
    subset,
    family: /font-family: '([^']+)'/.exec(body)?.[1],
    weight: /font-weight: (\d+)/.exec(body)?.[1],
    url: /url\((https:[^)]+)\)/.exec(body)?.[1],
    range: /unicode-range: ([^;]+);/.exec(body)?.[1],
  };
});

const rules = [];
const seen = new Set();
let total = 0;

for (const [family, plan] of Object.entries(PLAN)) {
  for (const subset of plan.subsets) {
    const matches = blocks.filter((b) => b.family === family && b.subset === subset && b.url);
    if (!matches.length) throw new Error(`no ${family} / ${subset}`);
    const weights = [...new Set(matches.map((m) => m.weight))].sort();

    for (const m of plan.variable ? [matches[0]] : matches) {
      const suffix = plan.variable ? "var" : m.weight;
      const file = `${plan.slug}-${suffix}-${subset}.woff2`;
      if (seen.has(file)) continue;
      seen.add(file);
      execFileSync("curl", ["-sS", "--fail", "-o", `${OUT}/${file}`, m.url]);
      total += readFileSync(`${OUT}/${file}`).length;
      rules.push([
        "@font-face {",
        `  font-family: "${family}";`,
        "  font-style: normal;",
        `  font-weight: ${plan.variable ? `${weights[0]} ${weights[weights.length - 1]}` : m.weight};`,
        ...(plan.stretch ? [`  font-stretch: ${plan.stretch};`] : []),
        "  font-display: swap;",
        `  src: url("./fonts/${file}") format("woff2");`,
        `  unicode-range: ${m.range};`,
        "}",
      ].join("\n"));
    }
  }
}

writeFileSync(
  join(ROOT, "public/fonts.css"),
  `/* Self-hosted type. The app makes no third-party request at runtime, so the
   promise on the intro screen — that nothing leaves your browser — is literal.
   Generated by scripts/fetch-fonts.mjs — edit that, not this.
   Licences and provenance in public/fonts/README.md. */

${rules.join("\n\n")}
`,
);

console.log(`${seen.size} files, ${(total / 1024).toFixed(0)}KB`);
for (const f of [...seen].sort()) console.log("  " + f);
